# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.5.1-14-gce9955c
_src_path: gh:coopiteasy/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 12.0
rebel_module_groups: []
repo_description: TODO
repo_name: Investor Wallet Platform
repo_slug: investor-wallet-platform
travis_apt_packages: []
travis_apt_sources: []
